//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.LopHocMonHocs = new HashSet<LopHocMonHoc>();
        }
    
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public string MaLoaiGV { get; set; }
        public string Email { get; set; }
        public string Sdt { get; set; }
    
        public virtual LoaiGV LoaiGV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHocMonHoc> LopHocMonHocs { get; set; }
    }
}
