//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string MaLog { get; set; }
        public System.DateTime ThoiGianCN { get; set; }
        public string TaiKhoanCN { get; set; }
        public string ThongTinCN { get; set; }
    }
}
