//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models.EF
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class LopHocMonHoc
    {
        public string MaLHMH { get; set; }
        public string MaLop { get; set; }
        public string MaMH { get; set; }
        public string MaGio { get; set; }
        public string MoTa { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayKT { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayBD { get; set; }
        public bool NgoaiGio { get; set; }
        public string MaGV { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual GioHoc GioHoc { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
