//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.LopHocMonHoc = new HashSet<LopHocMonHoc>();
        }
        [Required(ErrorMessage = "Mã lớp học không được rỗng")]
        public string MaLop { get; set; }
        public string MaCTDT { get; set; }
        [Required(ErrorMessage = "Tên lớp học không được rỗng")]
        [MaxLength(50, ErrorMessage = "Tên lớp học không được nhiều hơn 50 ký tự")]
        public string TenLop { get; set; }
        [Required(ErrorMessage = "Mô tả không được rỗng")]
        [MaxLength(50, ErrorMessage = "Mô tả không được nhiều hơn 50 ký tự")]
        public string MoTa { get; set; }
    
        public virtual CTDT CTDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHocMonHoc> LopHocMonHoc { get; set; }
    }
}
