//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.LopHocMonHoc = new HashSet<LopHocMonHoc>();
            this.MonHocHocKy = new HashSet<MonHocHocKy>();
        }
    
        public string MaMH { get; set; }
        [Required(ErrorMessage = "Tên môn học không được rỗng")]
        public string TenMon { get; set; }
        [Required(ErrorMessage = "Mô tả không được rỗng")]
        public string MoTa { get; set; }
        [Required(ErrorMessage = "Số giờ học không được rỗng")]
        [Range(0, int.MaxValue, ErrorMessage = "Giờ học phải là số")]
        public Nullable<decimal> SoGio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHocMonHoc> LopHocMonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonHocHocKy> MonHocHocKy { get; set; }
    }
}
