//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.GiaoVienMonHocs = new HashSet<GiaoVienMonHoc>();
            this.LopHocMonHocs = new HashSet<LopHocMonHoc>();
            this.MonHocHocKies = new HashSet<MonHocHocKy>();
        }
    
        public string MaMH { get; set; }
        [Required(ErrorMessage = "Tên môn học không được rỗng")]
        [MaxLength(50, ErrorMessage = "Tên môn học không được nhiều hơn 50 ký tự")]
        public string TenMon { get; set; }
        [Required(ErrorMessage = "Mô tả không được rỗng")]
        [MaxLength(150, ErrorMessage = "Tên môn học không được nhiều hơn 150 ký tự")]
        public string MoTa { get; set; }
        [Required(ErrorMessage = "Số giờ học không được rỗng")]
        [Range(1, int.MaxValue, ErrorMessage = "Giờ học phải là số lớn hơn 1")]
        public Nullable<decimal> SoGio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoVienMonHoc> GiaoVienMonHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHocMonHoc> LopHocMonHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonHocHocKy> MonHocHocKies { get; set; }
    }
}
