//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string MaTK { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public string MaGV { get; set; }
        public string MaVT { get; set; }
        public string HoTen { get; set; }
    
        public virtual VaiTro VaiTro { get; set; }
    }
}
