//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {

        public string MaTK { get; set; }
        [Required(ErrorMessage = "Tên đăng nhập không được rỗng")]
        public string TenDN { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được rỗng")]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "Mã giáo viên không được rỗng")]
        public string MaGV { get; set; }
        [Required(ErrorMessage = "Vai trò không được rỗng")]
        public string MaVT { get; set; }
        public string HoTen { get; set; }

        public virtual VaiTro VaiTro { get; set; }
    }
}
