//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiangDay.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {

        public string MaTK { get; set; }
        [Required(ErrorMessage = "Tên đăng nhập không được rỗng")]
        [MaxLength(10, ErrorMessage = "Tên đăng nhập không được nhiều hơn 10 ký tự")]
        public string TenDN { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được rỗng")]
        [MaxLength(150, ErrorMessage = "Mật khẩu không được nhiều hơn 150 ký tự")]
        public string MatKhau { get; set; }
        public string MaGV { get; set; }
        public string MaVT { get; set; }
        [MaxLength(10, ErrorMessage = "Họ và tên không dài quá 10 ký tự")]
        public string HoTen { get; set; }

        public virtual VaiTro VaiTro { get; set; }
    }
}
